In [1]:
pip install pandas

Collecting pandas
  Downloading pandas-3.0.5-cp311-cp311-win_amd64.whl.metadata (19 kB)
Requirement already satisfied: numpy>=1.26.0 in c:\Users\KK67\contoso\venv\Lib\site-packages (from pandas) (1.26.4)
Requirement already satisfied: python-dateutil>=2.8.2 in c:\Users\KK67\contoso\venv\Lib\site-packages (from pandas) (2.9.0.post0)
Collecting tzdata (from pandas)
  Downloading tzdata-2026.3-py2.py3-none-any.whl.metadata (1.4 kB)
Requirement already satisfied: six>=1.5 in c:\Users\KK67\contoso\venv\Lib\site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)
Downloading pandas-3.0.5-cp311-cp311-win_amd64.whl (10.0 MB)
   ---------------------------------------- 0.0/10.0 MB ? eta -:--:--
   - -------------------------------------- 0.3/10.0 MB ? eta -:--:--
   ---------- ----------------------------- 2.6/10.0 MB 11.6 MB/s eta 0:00:01
   ---------------- ----------------------- 4.2/10.0 MB 8.1 MB/s eta 0:00:01
   ----------------- ---------------------- 4.5/10.0 MB 6.7 MB/s eta 0:00:01
   ------------------------ --------------- 6.0/10.0 MB 6.6 MB/s eta 0:00:01
   ---------------------------- ----------- 7.1/10.0 MB 6.4 MB/s eta 0:00:01
   ----------------------------- ---------- 7.3/10.0 MB 6.3 MB/s eta 0:00:01
   ------------------------------ --------- 7.6/10.0 MB 5.5 MB/s eta 0:00:01
   ------------------------------- -------- 7.9/10.0 MB 4.9 MB/s eta 0:00:01
   --------------------------------- ------ 8.4/10.0 MB 4.3 MB/s eta 0:00:01
   ------------------------------------ --- 9.2/10.0 MB 4.2 MB/s eta 0:00:01
   ---------------------------------------- 10.0/10.0 MB 4.1 MB/s  0:00:02
Downloading tzdata-2026.3-py2.py3-none-any.whl (348 kB)
Installing collected packages: tzdata, pandas

   ---------------------------------------- 0/2 [tzdata]
   ---------------------------------------- 0/2 [tzdata]
   ---------------------------------------- 0/2 [tzdata]
   ---------------------------------------- 0/2 [tzdata]
   ---------------------------------------- 0/2 [tzdata]
   ---------------------------------------- 0/2 [tzdata]
   ---------------------------------------- 0/2 [tzdata]
   ---------------------------------------- 0/2 [tzdata]
   ---------------------------------------- 0/2 [tzdata]
   ---------------------------------------- 0/2 [tzdata]
   ---------------------------------------- 0/2 [tzdata]
   ---------------------------------------- 0/2 [tzdata]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   ---------------------------------------- 2/2 [pandas]

Successfully installed pandas-3.0.5 tzdata-2026.3
Note: you may need to restart the kernel to use updated packages.

In [1]:
import pandas as pd
import numpy as np

In [2]:
labels = ['a','b','c']
my_data = [10,20,30]
arr = np.array([10,20,30])
dict = {'a':10,'b':20,'c':30}

In [3]:
pd.Series(data=my_data)

0    10
1    20
2    30
dtype: int64

In [5]:
pd.Series(data=my_data,index=labels)

a    10
b    20
c    30
dtype: int64

In [6]:
pd.Series(arr)

0    10
1    20
2    30
dtype: int32

In [8]:
pd.Series(arr,labels)

a    10
b    20
c    30
dtype: int32

In [11]:
pd.Series(dict)

a    10
b    20
c    30
dtype: int64

In [12]:
pd.Series(data=labels)

0    a
1    b
2    c
dtype: str

In [13]:
pd.Series([sum,print,len])

0      <built-in function sum>
1    <built-in function print>
2      <built-in function len>
dtype: object

In [14]:
ser1= pd.Series([1,2,3,4], index=['USA','UK','Aus','Ind'])
ser1

USA    1
UK     2
Aus    3
Ind    4
dtype: int64

In [15]:
ser1= pd.Series([1,2,4], index=['USA','UK','Aus','Ind'])
ser1

ValueError: Length of values (3) does not match length of index (4)

In [16]:
ser2=pd.Series([1,2,5,4],index=['USA','UK','PAK','AFG'])
ser2

USA    1
UK     2
PAK    5
AFG    4
dtype: int64

In [17]:
ser2['USA']

1

In [18]:
ser2 + ser2

USA     2
UK      4
PAK    10
AFG     8
dtype: int64

Operations are then also done based off of index:

Pandas DATAFRAMES

In [20]:
import pandas as pd
import numpy as np

In [19]:
from numpy.random import randn
np.random.seed(101) # Here seed means that we get the same random number

In [69]:
df =pd.DataFrame(randn(5,4), index ='A B C D E'.split(), columns = 'W X Y Z'.split())

In [70]:
df

          W         X         Y         Z
A  0.302665  1.693723 -1.706086 -1.159119
B -0.134841  0.390528  0.166905  0.184502
C  0.807706  0.072960  0.638787  0.329646
D -0.497104 -0.754070 -0.943406  0.484752
E -0.116773  1.901755  0.238127  1.996652

## Selection and Indexing

Let's learn the various methods to grab data from a DataFrame

In [27]:
df['W']

A    2.706850
B    0.651118
C   -2.018168
D    0.188695
E    0.190794
Name: W, dtype: float64

In [29]:
df[['W','Z']]

          W         Z
A  2.706850  0.503826
B  0.651118  0.605965
C -2.018168 -0.589001
D  0.188695  0.955057
E  0.190794  0.683509

DataFrame Columns are just Series

In [31]:
type(df['W'])

pandas.Series

In [33]:
pd.Series([1,2,3,4], index='A B C D'.split())

A    1
B    2
C    3
D    4
dtype: int64

**Creating a new column:**

In [35]:
df['new'] = df['W'] + df['Y']

In [36]:
df

          W         X         Y         Z       new
A  2.706850  0.628133  0.907969  0.503826  3.614819
B  0.651118 -0.319318 -0.848077  0.605965 -0.196959
C -2.018168  0.740122  0.528813 -0.589001 -1.489355
D  0.188695 -0.758872 -0.933237  0.955057 -0.744542
E  0.190794  1.978757  2.605967  0.683509  2.796762

** Removing Columns**

In [39]:
df.drop('new', axis = 1)

          W         X         Y         Z
A  2.706850  0.628133  0.907969  0.503826
B  0.651118 -0.319318 -0.848077  0.605965
C -2.018168  0.740122  0.528813 -0.589001
D  0.188695 -0.758872 -0.933237  0.955057
E  0.190794  1.978757  2.605967  0.683509

In [42]:
# Not inplace unless specified!
df

          W         X         Y         Z       new
A  2.706850  0.628133  0.907969  0.503826  3.614819
B  0.651118 -0.319318 -0.848077  0.605965 -0.196959
C -2.018168  0.740122  0.528813 -0.589001 -1.489355
D  0.188695 -0.758872 -0.933237  0.955057 -0.744542
E  0.190794  1.978757  2.605967  0.683509  2.796762

In [43]:
df.drop('new', axis =1, inplace=True)

In [44]:
df

          W         X         Y         Z
A  2.706850  0.628133  0.907969  0.503826
B  0.651118 -0.319318 -0.848077  0.605965
C -2.018168  0.740122  0.528813 -0.589001
D  0.188695 -0.758872 -0.933237  0.955057
E  0.190794  1.978757  2.605967  0.683509

Can also drops rows with axis =0

In [45]:
df.drop('E',axis=0, inplace=True)

In [46]:
df

          W         X         Y         Z
A  2.706850  0.628133  0.907969  0.503826
B  0.651118 -0.319318 -0.848077  0.605965
C -2.018168  0.740122  0.528813 -0.589001
D  0.188695 -0.758872 -0.933237  0.955057

In [48]:
# Selecting rows

df.loc['A']

W    2.706850
X    0.628133
Y    0.907969
Z    0.503826
Name: A, dtype: float64

In [50]:
# Selecting rows based on index instead of names, index starts with 0

df.iloc[0]

W    2.706850
X    0.628133
Y    0.907969
Z    0.503826
Name: A, dtype: float64

** Selecting subset of rows and columns **

In [53]:
df.loc['B','Y']

-0.8480769834036315

In [55]:
df.loc[['A','B'],['X','Y']]

          X         Y
A  0.628133  0.907969
B -0.319318 -0.848077

Conditional Selection

In [56]:
df

          W         X         Y         Z
A  2.706850  0.628133  0.907969  0.503826
B  0.651118 -0.319318 -0.848077  0.605965
C -2.018168  0.740122  0.528813 -0.589001
D  0.188695 -0.758872 -0.933237  0.955057

In [57]:
df>0

       W      X      Y      Z
A   True   True   True   True
B   True  False  False   True
C  False   True   True  False
D   True  False  False   True

In [58]:
df[df>0]

          W         X         Y         Z
A  2.706850  0.628133  0.907969  0.503826
B  0.651118       NaN       NaN  0.605965
C       NaN  0.740122  0.528813       NaN
D  0.188695       NaN       NaN  0.955057

In [60]:
df[df['W']>0]

          W         X         Y         Z
A  2.706850  0.628133  0.907969  0.503826
B  0.651118 -0.319318 -0.848077  0.605965
D  0.188695 -0.758872 -0.933237  0.955057

In [61]:
df[df['W']>0]['Y']

A    0.907969
B   -0.848077
D   -0.933237
Name: Y, dtype: float64

In [62]:
df

          W         X         Y         Z
A  2.706850  0.628133  0.907969  0.503826
B  0.651118 -0.319318 -0.848077  0.605965
C -2.018168  0.740122  0.528813 -0.589001
D  0.188695 -0.758872 -0.933237  0.955057

In [64]:
df[df['W']>0][['Y','Z']]

          Y         Z
A  0.907969  0.503826
B -0.848077  0.605965
D -0.933237  0.955057

In [67]:
df[(df['W']>0) & (df['Y']<0)]

          W         X         Y         Z
B  0.651118 -0.319318 -0.848077  0.605965
D  0.188695 -0.758872 -0.933237  0.955057

## More Index Details

Let's discuss some more features of indexing, including resetting the index or setting it something else. We'll also talk about index hierarchy!

In [71]:
df

          W         X         Y         Z
A  0.302665  1.693723 -1.706086 -1.159119
B -0.134841  0.390528  0.166905  0.184502
C  0.807706  0.072960  0.638787  0.329646
D -0.497104 -0.754070 -0.943406  0.484752
E -0.116773  1.901755  0.238127  1.996652

In [72]:
df.reset_index()

  index         W         X         Y         Z
0     A  0.302665  1.693723 -1.706086 -1.159119
1     B -0.134841  0.390528  0.166905  0.184502
2     C  0.807706  0.072960  0.638787  0.329646
3     D -0.497104 -0.754070 -0.943406  0.484752
4     E -0.116773  1.901755  0.238127  1.996652

In [73]:
newind = 'NY TX CA LA BO'.split()

In [74]:
df['States'] = newind

In [75]:
df

          W         X         Y         Z States
A  0.302665  1.693723 -1.706086 -1.159119     NY
B -0.134841  0.390528  0.166905  0.184502     TX
C  0.807706  0.072960  0.638787  0.329646     CA
D -0.497104 -0.754070 -0.943406  0.484752     LA
E -0.116773  1.901755  0.238127  1.996652     BO

In [77]:
df.set_index('States')

               W         X         Y         Z
States
NY      0.302665  1.693723 -1.706086 -1.159119
TX     -0.134841  0.390528  0.166905  0.184502
CA      0.807706  0.072960  0.638787  0.329646
LA     -0.497104 -0.754070 -0.943406  0.484752
BO     -0.116773  1.901755  0.238127  1.996652

In [78]:
df

          W         X         Y         Z States
A  0.302665  1.693723 -1.706086 -1.159119     NY
B -0.134841  0.390528  0.166905  0.184502     TX
C  0.807706  0.072960  0.638787  0.329646     CA
D -0.497104 -0.754070 -0.943406  0.484752     LA
E -0.116773  1.901755  0.238127  1.996652     BO

In [80]:
df.set_index('States',inplace=True)

In [81]:
df

               W         X         Y         Z
States
NY      0.302665  1.693723 -1.706086 -1.159119
TX     -0.134841  0.390528  0.166905  0.184502
CA      0.807706  0.072960  0.638787  0.329646
LA     -0.497104 -0.754070 -0.943406  0.484752
BO     -0.116773  1.901755  0.238127  1.996652

## Multi-Index and Index Hierarchy

Let us go over how to work with Multi-Index, first we'll create a quick example of what a Multi-Indexed DataFrame would look like:

In [91]:
outside = ['G1','G1','G1','G2','G2','G2']
inside = [1,2,3,1,2,3]
hier_index = list(zip(outside,inside))
hier_index = pd.MultiIndex.from_tuples(hier_index)

In [92]:
hier_index

MultiIndex([('G1', 1),
            ('G1', 2),
            ('G1', 3),
            ('G2', 1),
            ('G2', 2),
            ('G2', 3)],
           )

In [93]:
df = pd.DataFrame(np.random.randn(6,2),index = hier_index, columns =['A','B'])

In [94]:
df

             A         B
G1 1  0.992573  1.192241
   2 -1.046780  1.292765
   3 -1.467514 -0.494095
G2 1 -0.162535  0.485809
   2  0.392489  0.221491
   3 -0.855196  1.541990

Now let's show how to index this! For index hierarchy we use df.loc[], if this was on the columns axis, you would just use normal bracket notation df[]. Calling one level of the index returns the sub-dataframe:

In [95]:
df.loc['G1']

          A         B
1  0.992573  1.192241
2 -1.046780  1.292765
3 -1.467514 -0.494095

In [97]:
df.loc['G1'].loc[1]

A    0.992573
B    1.192241
Name: 1, dtype: float64

In [99]:
df.index.names = ['Group','Numbers']

In [100]:
df

                      A         B
Group Numbers
G1    1        0.992573  1.192241
      2       -1.046780  1.292765
      3       -1.467514 -0.494095
G2    1       -0.162535  0.485809
      2        0.392489  0.221491
      3       -0.855196  1.541990

In [102]:
df.xs('G1')

                A         B
Numbers
1        0.992573  1.192241
2       -1.046780  1.292765
3       -1.467514 -0.494095

In [104]:
df.xs(('G1',1))

A    0.992573
B    1.192241
Name: (G1, 1), dtype: float64

In [106]:
df.xs(1,level='Numbers')

              A         B
Group
G1     0.992573  1.192241
G2    -0.162535  0.485809