# Missing Data

Let's show a few convenient methods to deal with Missing Data in pandas:

In [1]:
import numpy as np
import pandas as pd

In [6]:
df = pd.DataFrame({'A':[1,2,np.NaN],
                   'B':[5,np.NaN,np.NaN],
                   'C':[1,2,3]}, index='KK SUH BHA'.split())

In [7]:
df

       A    B  C
KK   1.0  5.0  1
SUH  2.0  NaN  2
BHA  NaN  NaN  3

In [8]:
df.dropna()

      A    B  C
KK  1.0  5.0  1

In [9]:
df.dropna(axis=1)

     C
KK   1
SUH  2
BHA  3

In [11]:
df.fillna(value='Fill Value')

              A           B  C
KK          1.0         5.0  1
SUH         2.0  Fill Value  2
BHA  Fill Value  Fill Value  3

In [12]:
df['A'].fillna(value=df['A'].mean())

KK     1.0
SUH    2.0
BHA    1.5
Name: A, dtype: float64