# Groupby

The groupby method allows you to group rows of data together and call aggregate functions

In [2]:
import pandas as pd
import numpy as np

In [23]:
data = {'Company':['GOOG','GOOG','META','META','CAPG','CAPG'],
        'Sales': [100,123,453,467,178,200],
         'Empname':['KK','Ajay','Suhu','Bhavana','Aswath','Vikram'] }

In [24]:
df = pd.DataFrame(data)

In [25]:
df

  Company  Sales  Empname
0    GOOG    100       KK
1    GOOG    123     Ajay
2    META    453     Suhu
3    META    467  Bhavana
4    CAPG    178   Aswath
5    CAPG    200   Vikram

In [26]:
df.groupby('Company')

In [27]:
by_comp = df.groupby("Company")

In [28]:
by_comp['Sales'].mean()

Company
CAPG    189.0
GOOG    111.5
META    460.0
Name: Sales, dtype: float64

In [32]:
by_comp['Sales'].std()

Company
CAPG    15.556349
GOOG    16.263456
META     9.899495
Name: Sales, dtype: float64

In [35]:
by_comp.min()

         Sales  Empname
Company
CAPG       178   Aswath
GOOG       100     Ajay
META       453  Bhavana

In [36]:
by_comp.max()

         Sales Empname
Company
CAPG       200  Vikram
GOOG       123      KK
META       467    Suhu

In [37]:
by_comp.count()

         Sales  Empname
Company
CAPG         2        2
GOOG         2        2
META         2        2

In [38]:
by_comp.describe()

        Sales
        count   mean        std    min     25%    50%     75%    max
Company
CAPG      2.0  189.0  15.556349  178.0  183.50  189.0  194.50  200.0
GOOG      2.0  111.5  16.263456  100.0  105.75  111.5  117.25  123.0
META      2.0  460.0   9.899495  453.0  456.50  460.0  463.50  467.0

In [ ]:
by_comp.describe().transpose() # just an example that you can transpose, the above one is more readable.

Company            CAPG        GOOG        META
Sales count    2.000000    2.000000    2.000000
      mean   189.000000  111.500000  460.000000
      std     15.556349   16.263456    9.899495
      min    178.000000  100.000000  453.000000
      25%    183.500000  105.750000  456.500000
      50%    189.000000  111.500000  460.000000
      75%    194.500000  117.250000  463.500000
      max    200.000000  123.000000  467.000000

In [41]:
by_comp.describe()

        Sales
        count   mean        std    min     25%    50%     75%    max
Company
CAPG      2.0  189.0  15.556349  178.0  183.50  189.0  194.50  200.0
GOOG      2.0  111.5  16.263456  100.0  105.75  111.5  117.25  123.0
META      2.0  460.0   9.899495  453.0  456.50  460.0  463.50  467.0

# Merging, Joining, and Concatenating

There are 3 main ways of combining DataFrames together: Merging, Joining and Concatenating. In this lecture we will discuss these 3 methods with examples.

____

In [46]:
data_MJC1 = {'A': ['A0','A1','A2','A3'],
             'B': ['B0','B1','B2','B3'],
             'C': ['C0','C1','C2','C3'],
             'D': ['D0','D1','D2','D3']}

In [47]:
df1 = pd.DataFrame(data_MJC1, index='0 1 2 3'.split())

In [48]:
df1

    A   B   C   D
0  A0  B0  C0  D0
1  A1  B1  C1  D1
2  A2  B2  C2  D2
3  A3  B3  C3  D3

In [49]:
data_MJC2= {'A': ['A4','A5','A6','A7'],
             'B': ['B4','B5','B6','B7'],
             'C': ['C4','C5','C6','C7'],
             'D': ['D4','D5','D6','D7']}

In [50]:
data_MJC3= {'A': ['A8','A9','A10','A11'],
             'B': ['B8','B9','B10','B11'],
             'C': ['C8','C9','C10','C11'],
             'D': ['D8','D9','D10','D11']}

In [57]:
df2 = pd.DataFrame(data_MJC2, index='4 5 6 7'.split())
df3 = pd.DataFrame(data_MJC3, index= '8 9 10 11'.split())

In [58]:
df2

    A   B   C   D
4  A4  B4  C4  D4
5  A5  B5  C5  D5
6  A6  B6  C6  D6
7  A7  B7  C7  D7

In [59]:
df3

      A    B    C    D
8    A8   B8   C8   D8
9    A9   B9   C9   D9
10  A10  B10  C10  D10
11  A11  B11  C11  D11

In [60]:
pd.concat((df1,df2,df3))

      A    B    C    D
0    A0   B0   C0   D0
1    A1   B1   C1   D1
2    A2   B2   C2   D2
3    A3   B3   C3   D3
4    A4   B4   C4   D4
5    A5   B5   C5   D5
6    A6   B6   C6   D6
7    A7   B7   C7   D7
8    A8   B8   C8   D8
9    A9   B9   C9   D9
10  A10  B10  C10  D10
11  A11  B11  C11  D11

In [61]:
pd.concat([df1,df2,df3], axis=1)

      A    B    C    D    A    B    C    D    A    B    C    D
0    A0   B0   C0   D0  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN
1    A1   B1   C1   D1  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN
2    A2   B2   C2   D2  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN
3    A3   B3   C3   D3  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN
4   NaN  NaN  NaN  NaN   A4   B4   C4   D4  NaN  NaN  NaN  NaN
5   NaN  NaN  NaN  NaN   A5   B5   C5   D5  NaN  NaN  NaN  NaN
6   NaN  NaN  NaN  NaN   A6   B6   C6   D6  NaN  NaN  NaN  NaN
7   NaN  NaN  NaN  NaN   A7   B7   C7   D7  NaN  NaN  NaN  NaN
8   NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN   A8   B8   C8   D8
9   NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN   A9   B9   C9   D9
10  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  A10  B10  C10  D10
11  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  A11  B11  C11  D11

_____
## Example DataFrames

In [62]:
left = pd.DataFrame({'Key':['Key0','Key1','Key2','Key3'],
                     'A': ['A0','A1','A2','A3'],
                     'B': ['B0','B1','B2','B3']
                     })

right = pd.DataFrame({'Key':['Key0','Key1','Key2','Key3'],
                      'C': ['C0','C1','C2','C3'],
                      'D': ['D0','D1','D2','D3']})

In [63]:
left

    Key   A   B
0  Key0  A0  B0
1  Key1  A1  B1
2  Key2  A2  B2
3  Key3  A3  B3

In [64]:
right

    Key   C   D
0  Key0  C0  D0
1  Key1  C1  D1
2  Key2  C2  D2
3  Key3  C3  D3

In [67]:
pd.merge(left,right, how='inner', on='Key')

    Key   A   B   C   D
0  Key0  A0  B0  C0  D0
1  Key1  A1  B1  C1  D1
2  Key2  A2  B2  C2  D2
3  Key3  A3  B3  C3  D3

## Joining
Joining is a convenient method for combining the columns of two potentially differently-indexed DataFrames into a single result DataFrame.

In [70]:
left1 = pd.DataFrame({'A': ['A0', 'A1', 'A2'],
                     'B': ['B0', 'B1', 'B2']},
                      index=['K0', 'K1', 'K2']) 

right1 = pd.DataFrame({'C': ['C0', 'C2', 'C3'],
                    'D': ['D0', 'D2', 'D3']},
                      index=['K0', 'K2', 'K3'])

In [71]:
left1.join(right1)

     A   B    C    D
K0  A0  B0   C0   D0
K1  A1  B1  NaN  NaN
K2  A2  B2   C2   D2

In [72]:
left1.join(right1, how='outer')

      A    B    C    D
K0   A0   B0   C0   D0
K1   A1   B1  NaN  NaN
K2   A2   B2   C2   D2
K3  NaN  NaN   C3   D3