In [1]:
import pandas as pd
import numpy as np

In [ ]:
df =pd.DataFrame({'col1':['1','2','3','4'],'col2':['444','555','666','444'],'col3':['abc','def','ijk','xyz']})
df.head()

  col1 col2 col3
0    1  444  abc
1    2  555  def
2    3  666  ijk
3    4  444  xyz

In [5]:
df['col2'].unique()

<StringArray>
['444', '555', '666']
Length: 3, dtype: str

In [6]:
df['col2'].nunique()

3

In [7]:
df['col2'].value_counts()

col2
444    2
555    1
666    1
Name: count, dtype: int64

In [22]:
df['col2'].values

<StringArray>
['444', '555', '666', '444']
Length: 4, dtype: str

I took the values of col1, col2 as string values instead of integers, that is why I had to convert them to numeric by using the below function, that is why str, int comparision errors are coming

In [ ]:
df1= pd.to_numeric(df['col1'])>2

In [33]:
df2=pd.to_numeric(df['col2'])>444

In [36]:
newdf = df[(df1)&(df2)]

In [37]:
newdf

  col1 col2 col3
2    3  666  ijk

Applying Functions

In [40]:
def times2(x):
    return x*2

In [42]:
df['col1'].apply(times2)  # The output is due to the col1 and col2 values are taken as string values

0    11
1    22
2    33
3    44
Name: col1, dtype: str

** Permanently Removing a Column**

In [44]:
del df['col1']

In [45]:
df

  col2 col3
0  444  abc
1  555  def
2  666  ijk
3  444  xyz

In [46]:
df.columns

Index(['col2', 'col3'], dtype='str')

In [47]:
df.index

RangeIndex(start=0, stop=4, step=1)

In [48]:
df.sort_index

<bound method DataFrame.sort_index of   col2 col3
0  444  abc
1  555  def
2  666  ijk
3  444  xyz>

In [49]:
df.sort_values(by='col2') #inplace=False by default

  col2 col3
0  444  abc
3  444  xyz
1  555  def
2  666  ijk

In [50]:
df.isnull() # to find any null values

    col2   col3
0  False  False
1  False  False
2  False  False
3  False  False

In [55]:
nu_df =pd.DataFrame({'col1':[1,2,3,np.NaN],
                     'col2':[444,np.NaN,555,786],
                     'col3':['Good','Bad','Ugly','Successful']})

In [56]:
nu_df

   col1   col2        col3
0   1.0  444.0        Good
1   2.0    NaN         Bad
2   3.0  555.0        Ugly
3   NaN  786.0  Successful

In [58]:
nu_df.fillna('FILL')

   col1   col2        col3
0   1.0  444.0        Good
1   2.0   FILL         Bad
2   3.0  555.0        Ugly
3  FILL  786.0  Successful

In [59]:
data5 = {'A':['foo','foo','foo','bar','bar','bar'],
     'B':['one','one','two','two','one','one'],
       'C':['x','y','x','y','x','y'],
       'D':[1,3,2,5,4,1]}

In [63]:
nedf = pd.DataFrame(data5)

In [67]:
nedf.pivot_table(values='D',index=['A','B'], columns =['C'] )

C          x    y
A   B
bar one  4.0  1.0
    two  NaN  5.0
foo one  1.0  3.0
    two  2.0  NaN