# Finance Data Project - Solutions

In this data project we will focus on exploratory data analysis of stock prices. Keep in mind, this project is just meant to practice your visualization and pandas skills, it is not meant to be a robust financial analysis or be taken as financial advice.
____
** NOTE: This project is extremely challenging because it will introduce a lot of new concepts and have you looking things up on your own (we'll point you in the right direction) to try to solve the tasks issued. Feel free to just go through the solutions lecture notebook and video as a "walkthrough" project if you don't want to have to look things up yourself. You'll still learn a lot that way! **
____
We'll focus on bank stocks and see how they progressed throughout the [financial crisis](https://en.wikipedia.org/wiki/Financial_crisis_of_2007%E2%80%9308) all the way to early 2016.

## Get the Data

In this section we will learn how to use pandas to directly read data from Google finance using pandas!

First we need to start with the proper imports, which we've already laid out for you here.

*Note: [You'll need to install pandas-datareader for this to work!](https://github.com/pydata/pandas-datareader) Pandas datareader allows you to [read stock information directly from the internet](http://pandas.pydata.org/pandas-docs/stable/remote_data.html) Use these links for install guidance (**pip install pandas-datareader**), or just follow along with the video lecture.*

### The Imports

Already filled out for you.

In [6]:
pip install pandas-datareader

Collecting pandas-datareader
  Downloading pandas_datareader-0.11.1-py3-none-any.whl.metadata (3.8 kB)
Requirement already satisfied: lxml in c:\Users\KK67\contoso\venv\Lib\site-packages (from pandas-datareader) (6.1.1)
Requirement already satisfied: pandas>=2.1.4 in c:\Users\KK67\contoso\venv\Lib\site-packages (from pandas-datareader) (3.0.5)
Requirement already satisfied: requests>=2.19.0 in c:\Users\KK67\contoso\venv\Lib\site-packages (from pandas-datareader) (2.31.0)
Requirement already satisfied: setuptools in c:\Users\KK67\contoso\venv\Lib\site-packages (from pandas-datareader) (65.5.0)
Requirement already satisfied: numpy>=1.26.0 in c:\Users\KK67\contoso\venv\Lib\site-packages (from pandas>=2.1.4->pandas-datareader) (1.26.4)
Requirement already satisfied: python-dateutil>=2.8.2 in c:\Users\KK67\contoso\venv\Lib\site-packages (from pandas>=2.1.4->pandas-datareader) (2.9.0.post0)
Requirement already satisfied: tzdata in c:\Users\KK67\contoso\venv\Lib\site-packages (from pandas>=2.1.4->pandas-datareader) (2026.3)
Requirement already satisfied: six>=1.5 in c:\Users\KK67\contoso\venv\Lib\site-packages (from python-dateutil>=2.8.2->pandas>=2.1.4->pandas-datareader) (1.17.0)
Requirement already satisfied: charset-normalizer<4,>=2 in c:\Users\KK67\contoso\venv\Lib\site-packages (from requests>=2.19.0->pandas-datareader) (3.3.2)
Requirement already satisfied: idna<4,>=2.5 in c:\Users\KK67\contoso\venv\Lib\site-packages (from requests>=2.19.0->pandas-datareader) (3.6)
Requirement already satisfied: urllib3<3,>=1.21.1 in c:\Users\KK67\contoso\venv\Lib\site-packages (from requests>=2.19.0->pandas-datareader) (2.2.1)
Requirement already satisfied: certifi>=2017.4.17 in c:\Users\KK67\contoso\venv\Lib\site-packages (from requests>=2.19.0->pandas-datareader) (2024.2.2)
Downloading pandas_datareader-0.11.1-py3-none-any.whl (65 kB)
Installing collected packages: pandas-datareader
Successfully installed pandas-datareader-0.11.1
Note: you may need to restart the kernel to use updated packages.

[notice] A new release of pip is available: 26.1.2 -> 26.2.1
[notice] To update, run: python.exe -m pip install --upgrade pip

In [2]:
from pandas_datareader import data,wb
import pandas as pd
import numpy as np
import datetime
%matplotlib inline

## Data

We need to get data using pandas datareader. We will get stock information for the following banks:
*  Bank of America
* CitiGroup
* Goldman Sachs
* JPMorgan Chase
* Morgan Stanley
* Wells Fargo

** Figure out how to get the stock data from Jan 1st 2006 to Jan 1st 2016 for each of these banks. Set each bank to be a separate dataframe, with the variable name for that bank being its ticker symbol. This will involve a few steps:**
1. Use datetime to set start and end datetime objects.
2. Figure out the ticker symbol for each bank.
2. Figure out how to use datareader to grab info on the stock.

** Use [this documentation page](https://pandas-datareader.readthedocs.io/en/latest/remote_data.html) for hints and instructions (it should just be a matter of replacing certain values. Use google finance as a source, for example:**
    
    # Bank of America
    BAC = data.DataReader("BAC", 'google', start, end)

### WARNING: MAKE SURE TO CHECK THE LINK ABOVE FOR THE LATEST WORKING API. "google" MAY NOT ALWAYS WORK.

In [3]:
start = datetime.datetime(2006,1,1)
end = datetime.datetime(2016,1,1)

In [5]:
import yfinance as yf

BAC = yf.download("BAC",start=start,end=end)

Cookie fetch from fc.yahoo.com failed (CertificateVerifyError), continuing without it
Cookie/crumb fetch failed (CertificateVerifyError), continuing without crumb
[*********************100%***********************]  1 of 1 completed

In [6]:
BAC.head()

Price           Close       High        Low       Open    Volume
Ticker            BAC        BAC        BAC        BAC       BAC
Date
2006-01-03  30.176376  30.240471  29.580284  30.073820  16296700
2006-01-04  29.855907  30.278941  29.772582  30.125109  17757900
2006-01-05  29.894356  30.016140  29.689249  29.855900  14970700
2006-01-06  29.849487  30.067414  29.708475  29.996908  12599800
2006-01-09  29.868723  30.105880  29.714894  29.945640  15619400

In [7]:
# CitiGroup
C = yf.download("C",start, end)

# Goldman Sachs
GS = yf.download("GS",start, end)

# JPMorgan Chase
JPM = yf.download("JPM",start, end)

# Morgan Stanley
MS = yf.download("MS",start, end)

# Wells Fargo
WFC = yf.download("WFC",start, end)

Cookie/crumb fetch failed (CertificateVerifyError), continuing without crumb
[*********************100%***********************]  1 of 1 completed
Cookie/crumb fetch failed (CertificateVerifyError), continuing without crumb
[*********************100%***********************]  1 of 1 completed
Cookie/crumb fetch failed (CertificateVerifyError), continuing without crumb
[*********************100%***********************]  1 of 1 completed
Cookie/crumb fetch failed (CertificateVerifyError), continuing without crumb
[*********************100%***********************]  1 of 1 completed
Cookie/crumb fetch failed (CertificateVerifyError), continuing without crumb
[*********************100%***********************]  1 of 1 completed

In [8]:
tickers = ['BAC', 'C', 'GS', 'JPM', 'MS', 'WFC']

** Use pd.concat to concatenate the bank dataframes together to a single data frame called bank_stocks. Set the keys argument equal to the tickers list. Also pay attention to what axis you concatenate on.**

In [10]:
bank_stocks = pd.concat([BAC, C, GS, JPM,MS, WFC],axis = 1, keys = tickers)

In [13]:
print(bank_stocks.columns)
print(bank_stocks.columns.nlevels)

MultiIndex([('BAC',  'Close', 'BAC'),
            ('BAC',   'High', 'BAC'),
            ('BAC',    'Low', 'BAC'),
            ('BAC',   'Open', 'BAC'),
            ('BAC', 'Volume', 'BAC'),
            (  'C',  'Close',   'C'),
            (  'C',   'High',   'C'),
            (  'C',    'Low',   'C'),
            (  'C',   'Open',   'C'),
            (  'C', 'Volume',   'C'),
            ( 'GS',  'Close',  'GS'),
            ( 'GS',   'High',  'GS'),
            ( 'GS',    'Low',  'GS'),
            ( 'GS',   'Open',  'GS'),
            ( 'GS', 'Volume',  'GS'),
            ('JPM',  'Close', 'JPM'),
            ('JPM',   'High', 'JPM'),
            ('JPM',    'Low', 'JPM'),
            ('JPM',   'Open', 'JPM'),
            ('JPM', 'Volume', 'JPM'),
            ( 'MS',  'Close',  'MS'),
            ( 'MS',   'High',  'MS'),
            ( 'MS',    'Low',  'MS'),
            ( 'MS',   'Open',  'MS'),
            ( 'MS', 'Volume',  'MS'),
            ('WFC',  'Close', 'WFC'),
            ('WFC',   'High', 'WFC'),
            ('WFC',    'Low', 'WFC'),
            ('WFC',   'Open', 'WFC'),
            ('WFC', 'Volume', 'WFC')],
           names=[None, 'Price', 'Ticker'])
3

** Set the column name levels (this is filled out for you):**

In [14]:
bank_stocks.columns.names = ['Bank ticker','stock info']

ValueError: Length of names must match number of levels in MultiIndex.

In [15]:
bank_stocks.head()

                  BAC                                                      C  \
Price           Close       High        Low       Open    Volume       Close
Ticker            BAC        BAC        BAC        BAC       BAC           C
Date
2006-01-03  30.176376  30.240471  29.580284  30.073820  16296700  312.726715
2006-01-04  29.855907  30.278941  29.772582  30.125109  17757900  306.953156
2006-01-05  29.894356  30.016140  29.689249  29.855900  14970700  308.475830
2006-01-06  29.849487  30.067414  29.708475  29.996908  12599800  308.475830
2006-01-09  29.868723  30.105880  29.714894  29.945640  15619400  307.016541

                                                         ...         MS  \
Price             High         Low        Open   Volume  ...      Close
Ticker               C           C           C        C  ...         MS
Date                                                     ...
2006-01-03  313.297728  305.240062  310.886777  1537600  ...  31.011353
2006-01-04  311.521296  306.762824  309.998589  1870960  ...  31.032616
2006-01-05  309.490955  307.080004  307.333785  1143160  ...  31.117701
2006-01-06  310.252318  305.811078  310.125418  1370210  ...  31.149614
2006-01-09  309.237160  306.445528  308.348916  1680740  ...  31.479349

                                                            WFC             \
Price            High        Low       Open   Volume      Close       High
Ticker             MS         MS         MS       MS        WFC        WFC
Date
2006-01-03  31.107083  30.176370  30.405058  5377000  18.170349  18.213070
2006-01-04  31.527223  31.032616  31.218759  7977800  17.959591  18.124775
2006-01-05  31.160248  30.857102  31.138974  5778000  17.939655  17.973831
2006-01-06  31.298528  30.873060  31.255982  6889800  18.045036  18.099148
2006-01-09  31.532534  31.176203  31.181522  4144500  18.042187  18.127628


Price             Low       Open    Volume
Ticker            WFC        WFC       WFC
Date
2006-01-03  17.768779  17.999469  11016400
2006-01-04  17.865606  18.113383  10870000
2006-01-05  17.834278  17.942503  10158000
2006-01-06  17.877003  17.988076   8403800
2006-01-09  17.973835  18.042187   5619600

[5 rows x 30 columns]

In [16]:
bank_stocks.xs(key='Close',axis=1).max()

KeyError: 'Close'